version: '3.9'

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
    volumes:
      - ./api:/app
